import { useEffect,useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Link } from "@tanstack/react-router";
import { PageHeader,Panel,StatCard,StatusBadge } from "@/components/shared/kit";
import { supabase } from "@/lib/supabase";
type Counts={users:number;sites:number;campaigns:number;queued:number;workers:number;credits:number};
export const Route=createFileRoute("/admin/")({component:AdminDashboard});
function AdminDashboard(){const [c,setC]=useState<Counts>({users:0,sites:0,campaigns:0,queued:0,workers:0,credits:0});const [loading,setLoading]=useState(true);
useEffect(()=>{void(async()=>{const [u,s,ca,j,w,cr]=await Promise.all([supabase.from("profiles").select("id",{count:"exact",head:true}),supabase.from("sites").select("id",{count:"exact",head:true}),supabase.from("campaigns").select("id",{count:"exact",head:true}),supabase.from("jobs").select("id",{count:"exact",head:true}).eq("status","queued"),supabase.from("workers").select("id",{count:"exact",head:true}).neq("status","offline"),supabase.from("credit_balances").select("balance")]);setC({users:u.count??0,sites:s.count??0,campaigns:ca.count??0,queued:j.count??0,workers:w.count??0,credits:(cr.data??[]).reduce((n,x)=>n+Number(x.balance||0),0)});setLoading(false)})()},[]);
return <div><PageHeader title="Admin Dashboard" description="Visão operacional do Traffic Navigator."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><StatCard label="Usuários" value={loading?"…":c.users}/><StatCard label="Sites" value={loading?"…":c.sites}/><StatCard label="Campanhas" value={loading?"…":c.campaigns}/><StatCard label="Na fila" value={loading?"…":c.queued} tone="warning"/><StatCard label="Workers ativos" value={loading?"…":c.workers} tone="success"/><StatCard label="Créditos em contas" value={loading?"…":c.credits.toLocaleString("pt-BR")} /></div><Panel title="Operação" description="Atalhos para as áreas administrativas." className="mt-6"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[["/admin/usuarios","Usuários"],["/admin/campanhas","Campanhas"],["/admin/tarefas","Fila de tarefas"],["/admin/creditos","Créditos"],["/admin/planos","Planos"],["/admin/workers","Workers"],["/admin/logs","Logs"]].map(([to,label])=><Link key={to} to={to as any} className="rounded-lg border p-4 text-sm font-medium hover:bg-muted/50">{label}</Link>)}</div></Panel></div>}