import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Field, PageHeader, Panel, DataTable, StatusBadge } from "@/components/shared/kit";
import { supabase } from "@/lib/supabase";

type Plan={id:string;name:string;tagline:string;price_monthly:number|null;credits_monthly:number;max_sites:number|null;max_campaigns:number|null;highlighted:boolean;is_trial:boolean};
const blank={name:"",tagline:"",price_monthly:"",credits_monthly:"1000",max_sites:"1",max_campaigns:"3",highlighted:false,is_trial:false};
export const Route=createFileRoute("/admin/planos")({component:AdminPlans});

function AdminPlans(){
 const [plans,setPlans]=useState<Plan[]>([]); const [form,setForm]=useState(blank); const [editing,setEditing]=useState<string|null>(null); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from("plans").select("*").order("price_monthly",{ascending:true,nullsFirst:true});if(error)setMessage(error.message);setPlans((data??[]) as Plan[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const save=async()=>{setMessage("");const payload={name:form.name.trim(),tagline:form.tagline.trim(),price_monthly:form.price_monthly===""?null:Number(form.price_monthly),credits_monthly:Number(form.credits_monthly),max_sites:form.max_sites===""?null:Number(form.max_sites),max_campaigns:form.max_campaigns===""?null:Number(form.max_campaigns),highlighted:form.highlighted,is_trial:form.is_trial};if(!payload.name||payload.credits_monthly<0){setMessage("Informe nome e créditos válidos.");return}setLoading(true);const q=editing?supabase.from("plans").update(payload).eq("id",editing).select("*").single():supabase.from("plans").insert(payload).select("*").single();const {error}=await q;if(error)setMessage(error.message);else{setMessage(editing?"Plano atualizado.":"Plano criado.");setForm(blank);setEditing(null);await load()}setLoading(false)};
 const edit=(p:Plan)=>setForm({name:p.name,tagline:p.tagline,price_monthly:p.price_monthly==null?"":String(p.price_monthly),credits_monthly:String(p.credits_monthly),max_sites:p.max_sites==null?"":String(p.max_sites),max_campaigns:p.max_campaigns==null?"":String(p.max_campaigns),highlighted:p.highlighted,is_trial:p.is_trial});
 const remove=async(id:string)=>{if(!window.confirm("Excluir este plano?"))return;setLoading(true);const {error}=await supabase.from("plans").delete().eq("id",id);if(error)setMessage(error.message);else await load();setLoading(false)};
 return <div><PageHeader title="Planos" description="Catálogo comercial conectado ao Supabase. O cliente final poderá consumir estes planos na área pública."/>
 <Panel title={editing?"Editar plano":"Novo plano"}>
 <div className="grid gap-4 md:grid-cols-3"><Field label="Nome"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="h-9 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Descrição curta"><input value={form.tagline} onChange={e=>setForm({...form,tagline:e.target.value})} className="h-9 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Preço mensal (BRL)"><input type="number" min="0" step="0.01" value={form.price_monthly} onChange={e=>setForm({...form,price_monthly:e.target.value})} className="h-9 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Créditos/mês"><input type="number" min="0" step="1" value={form.credits_monthly} onChange={e=>setForm({...form,credits_monthly:e.target.value})} className="h-9 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Máx. sites"><input type="number" min="0" value={form.max_sites} onChange={e=>setForm({...form,max_sites:e.target.value})} className="h-9 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Máx. campanhas"><input type="number" min="0" value={form.max_campaigns} onChange={e=>setForm({...form,max_campaigns:e.target.value})} className="h-9 w-full rounded-md border bg-background px-3 text-sm"/></Field></div>
 <div className="mt-4 flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={form.highlighted} onChange={e=>setForm({...form,highlighted:e.target.checked})}/> Destaque</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.is_trial} onChange={e=>setForm({...form,is_trial:e.target.checked})}/> Trial</label></div>
 <div className="mt-4 flex gap-2"><Button onClick={()=>void save()} disabled={loading}>{loading?"Salvando…":editing?"Salvar alterações":"Criar plano"}</Button>{editing&&<Button variant="outline" onClick={()=>{setEditing(null);setForm(blank)}}>Cancelar</Button>}</div>{message&&<p className="mt-3 text-sm text-muted-foreground">{message}</p>}</Panel>
 <div className="mt-4"><DataTable rows={plans} rowKey={p=>p.id} columns={[{key:"name",header:"Plano",cell:p=><div><span className="font-medium">{p.name}</span>{p.highlighted&&<span className="ml-2"><StatusBadge status="active"/></span>}</div>},{key:"price",header:"Preço",cell:p=>p.price_monthly==null?"Sob consulta":`R$ ${Number(p.price_monthly).toFixed(2).replace(".",",")}`},{key:"credits",header:"Créditos",cell:p=>p.credits_monthly.toLocaleString("pt-BR")},{key:"limits",header:"Limites",cell:p=>`${p.max_sites??"∞"} sites / ${p.max_campaigns??"∞"} campanhas`},{key:"actions",header:"Ações",cell:p=><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>{setEditing(p.id);edit(p)}}>Editar</Button><Button size="sm" variant="destructive" onClick={()=>void remove(p.id)}>Excluir</Button></div>}]}/></div></div>;
}