import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { DemoBanner, Field, NativeSelect, Panel, PageHeader } from "@/components/shared/kit";
import { campaignRepo } from "@/services/campaigns";
import { emptyDraft } from "@/mocks/demo";
import type { CampaignDraft } from "@/domain/types";
const steps = ["Site", "Sessão", "Páginas", "Origens", "Localização", "Volume", "Horários", "Revisão"];
export const Route = createFileRoute("/app/campanhas/nova")({ component: NewCampaign });
function NewCampaign() {
  const navigate = useNavigate(); const [step,setStep]=useState(0); const [draft,setDraft]=useState<CampaignDraft>(()=>emptyDraft()); const [error,setError]=useState("");
  const estimatedCredits=useMemo(()=>Math.ceil(draft.settings.total_sessions*(0.8+draft.settings.pages_per_session*0.1)),[draft.settings.total_sessions,draft.settings.pages_per_session]);
  const update=(patch:Partial<CampaignDraft>)=>setDraft((d)=>({...d,...patch}));
  const settings=(patch:Partial<CampaignDraft["settings"]>)=>update({settings:{...draft.settings,...patch}});
  const volume=(patch:Partial<CampaignDraft["volume"]>)=>update({volume:{...draft.volume,...patch}});
  const schedule=(patch:Partial<CampaignDraft["schedule"]>)=>update({schedule:{...draft.schedule,...patch}});
  const validate=()=>{if(step===0&&(!draft.name.trim()||!draft.site_id||!draft.start_url.trim()))return "Informe nome, site e URL inicial.";if(step===1&&(draft.settings.pages_per_session<1||draft.settings.min_duration_sec<1||draft.settings.max_duration_sec<draft.settings.min_duration_sec))return "Revise os parâmetros da sessão.";if(step===5&&(draft.volume.daily_limit<1||draft.volume.interval_min_sec<1||draft.volume.interval_max_sec<draft.volume.interval_min_sec))return "Revise os parâmetros de volume.";if(step===6&&(!draft.schedule.start_time||!draft.schedule.end_time||draft.schedule.weekdays.length===0))return "Escolha horário e pelo menos um dia.";return "";};
  const next=()=>{const message=validate();if(message)return setError(message);setError("");setStep((s)=>Math.min(7,s+1));};
  const save=(status:"draft"|"active")=>{const message=validate();if(message||!draft.name.trim()||!draft.site_id||!draft.start_url.trim())return setError(message||"Complete os campos obrigatórios.");const campaign=campaignRepo.create(draft,status);navigate({to:"/app/campanhas/$id",params:{id:campaign.id}});};
  const toggleDay=(day:0|1|2|3|4|5|6)=>schedule({weekdays:draft.schedule.weekdays.includes(day)?draft.schedule.weekdays.filter((d)=>d!==day):[...draft.schedule.weekdays,day].sort() as CampaignDraft["schedule"]["weekdays"]});
  return <div><DemoBanner>O assistente funciona no navegador e cria campanhas no armazenamento de demonstração. A execução real será ligada depois à API, fila e workers.</DemoBanner>
    <PageHeader title="Nova campanha" description="Configure e revise uma jornada de teste em 8 etapas." />
    <div className="mb-6 grid gap-2 md:grid-cols-8">{steps.map((name,i)=><button key={name} type="button" onClick={()=>i<=step&&setStep(i)} className={"rounded-lg border p-3 text-left "+(i===step?"border-primary bg-primary/5":"bg-card")}><span className="font-mono text-xs text-primary">{"0"+(i+1)}</span><p className="mt-1 text-sm font-medium">{name}</p></button>)}</div>
    <Panel title={"Etapa "+(step+1)+" — "+steps[step]} description="Os dados ficam preparados para a futura persistência.">
      {step===0&&<div className="grid gap-5 md:grid-cols-2"><Field label="Nome"><input value={draft.name} onChange={(e)=>update({name:e.target.value})} placeholder="Ex.: Jornada de navegação" className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Site"><NativeSelect value={draft.site_id} onChange={(e)=>update({site_id:e.target.value})}><option value="">Selecione</option><option value="site-1">Loja Exemplo — loja-exemplo.com.br</option><option value="site-2">Blog Exemplo — blog-exemplo.com</option></NativeSelect></Field><Field label="URL inicial"><input type="url" value={draft.start_url} onChange={(e)=>update({start_url:e.target.value})} placeholder="https://seusite.com.br/" className="h-10 w-full rounded-md border bg-background px-3 text-sm md:col-span-2"/></Field><Field label="Sitemap XML (opcional)"><input type="url" value={draft.sitemap_url} onChange={(e)=>update({sitemap_url:e.target.value})} placeholder="https://seusite.com.br/sitemap.xml" className="h-10 w-full rounded-md border bg-background px-3 text-sm md:col-span-2"/></Field></div>}
      {step===1&&<div className="grid gap-5 md:grid-cols-2"><Field label="Sessões"><input type="number" min="1" value={draft.settings.total_sessions} onChange={(e)=>settings({total_sessions:Number(e.target.value)})} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Páginas por sessão"><input type="number" min="1" value={draft.settings.pages_per_session} onChange={(e)=>settings({pages_per_session:Number(e.target.value)})} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Duração mínima (s)"><input type="number" min="1" value={draft.settings.min_duration_sec} onChange={(e)=>settings({min_duration_sec:Number(e.target.value)})} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Duração máxima (s)"><input type="number" min="1" value={draft.settings.max_duration_sec} onChange={(e)=>settings({max_duration_sec:Number(e.target.value)})} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Desktop (%)"><input type="number" min="0" max="100" value={draft.settings.desktop_pct} onChange={(e)=>settings({desktop_pct:Number(e.target.value)})} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Novos visitantes (%)"><input type="number" min="0" max="100" value={draft.settings.new_visitor_pct} onChange={(e)=>settings({new_visitor_pct:Number(e.target.value)})} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><p className="text-xs text-muted-foreground md:col-span-2">A futura execução poderá variar jornadas, duração, páginas e horários para cobertura de testes. Não inclui técnicas de evasão ou mascaramento de origem.</p></div>}
      {step===2&&<Field label="URLs da jornada" hint="Uma URL por linha. A futura análise de sitemap poderá preencher esta lista automaticamente."><textarea rows={8} value={draft.pages.map((p)=>p.url).join("\n")} onChange={(e)=>update({pages:e.target.value.split("\n").map((url,i)=>({id:"page-"+i,url:url.trim(),weight:1})).filter((p)=>p.url)})} className="w-full rounded-md border bg-background px-3 py-2 text-sm" placeholder={"https://seusite.com.br/\nhttps://seusite.com.br/produto"}/></Field>}
      {step===3&&<div className="grid gap-3 md:grid-cols-2">{[["direct","Direto"],["search","Busca"],["social","Social"],["referral","Referência"]].map(([type,label])=>{const exists=draft.sources.some((s)=>s.type===type);return <label key={type} className="flex items-center justify-between rounded-lg border p-4"><span className="font-medium">{label}</span><input type="checkbox" checked={exists} onChange={(e)=>update({sources:e.target.checked?[...draft.sources,{id:"src-"+type,type:type as CampaignDraft["sources"][number]["type"],label,weight:1}]:draft.sources.filter((s)=>s.type!==type)})}/></label>;})}</div>}
      {step===4&&<div className="grid gap-5 md:grid-cols-2"><Field label="País"><NativeSelect value={draft.location.country} onChange={(e)=>update({location:{...draft.location,country:e.target.value}})}><option value="BR">Brasil</option><option value="PT">Portugal</option><option value="US">Estados Unidos</option></NativeSelect></Field><Field label="Região"><input value={draft.location.region} onChange={(e)=>update({location:{...draft.location,region:e.target.value}})} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Cidade"><input value={draft.location.city} onChange={(e)=>update({location:{...draft.location,city:e.target.value}})} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Fuso horário"><NativeSelect value={draft.location.timezone} onChange={(e)=>update({location:{...draft.location,timezone:e.target.value},schedule:{...draft.schedule,timezone:e.target.value}})}><option value="America/Sao_Paulo">America/Sao_Paulo</option><option value="America/New_York">America/New_York</option><option value="Europe/Lisbon">Europe/Lisbon</option></NativeSelect></Field></div>}
      {step===5&&<div className="grid gap-5 md:grid-cols-2"><Field label="Limite diário"><input type="number" min="1" value={draft.volume.daily_limit} onChange={(e)=>volume({daily_limit:Number(e.target.value)})} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Distribuição"><NativeSelect value={draft.volume.distribution} onChange={(e)=>volume({distribution:e.target.value as "fixed"|"variable"})}><option value="variable">Variável</option><option value="fixed">Fixa</option></NativeSelect></Field><Field label="Intervalo mínimo (s)"><input type="number" min="1" value={draft.volume.interval_min_sec} onChange={(e)=>volume({interval_min_sec:Number(e.target.value)})} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Intervalo máximo (s)"><input type="number" min="1" value={draft.volume.interval_max_sec} onChange={(e)=>volume({interval_max_sec:Number(e.target.value)})} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><div className="rounded-lg bg-muted/50 p-4 text-sm md:col-span-2">Estimativa: <strong>{estimatedCredits.toLocaleString("pt-BR")} créditos</strong>.</div></div>}
      {step===6&&<div className="space-y-5"><div className="grid gap-5 md:grid-cols-3"><Field label="Início"><input type="time" value={draft.schedule.start_time} onChange={(e)=>schedule({start_time:e.target.value})} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Fim"><input type="time" value={draft.schedule.end_time} onChange={(e)=>schedule({end_time:e.target.value})} className="h-10 w-full rounded-md border bg-background px-3 text-sm"/></Field><Field label="Distribuição"><NativeSelect value={draft.schedule.distribution} onChange={(e)=>schedule({distribution:e.target.value as "even"|"peak"})}><option value="even">Uniforme</option><option value="peak">Picos</option></NativeSelect></Field></div><Field label="Dias"><div className="flex flex-wrap gap-2">{["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"].map((label,day)=><button key={label} type="button" onClick={()=>toggleDay(day as 0|1|2|3|4|5|6)} className={"rounded-full border px-3 py-1.5 text-sm "+(draft.schedule.weekdays.includes(day as 0|1|2|3|4|5|6)?"border-primary bg-primary text-primary-foreground":"")}>{label}</button>)}</div></Field></div>}
      {step===7&&<div className="grid gap-3 md:grid-cols-2">{[["Campanha",draft.name],["URL inicial",draft.start_url],["Sessões",String(draft.settings.total_sessions)],["Páginas/sessão",String(draft.settings.pages_per_session)],["Janela",draft.schedule.start_time+" — "+draft.schedule.end_time],["Créditos estimados",estimatedCredits.toLocaleString("pt-BR")]].map(([label,value])=><div key={label} className="rounded-lg border p-4"><span className="text-xs text-muted-foreground">{label}</span><p className="mt-1 break-all font-medium">{value||"—"}</p></div>)}</div>}
      {error&&<div role="alert" className="mt-5 rounded-lg border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}
      <div className="mt-6 flex flex-col-reverse gap-2 border-t pt-5 sm:flex-row sm:justify-between"><button type="button" onClick={()=>step?setStep(step-1):navigate({to:"/app/campanhas"})} className="h-10 rounded-md border px-4 text-sm font-medium">Voltar</button><div className="flex gap-2"><button type="button" onClick={()=>save("draft")} className="h-10 rounded-md border px-4 text-sm font-medium">Salvar rascunho</button>{step<7?<button type="button" onClick={next} className="h-10 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground">Continuar</button>:<button type="button" onClick={()=>save("active")} className="h-10 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground">Ativar campanha</button>}</div></div>
    </Panel></div>;
}